region	            = "eu-west-1"

frontend_name	    = "testAircalldev"

web_instance_type   = "t2.micro"
key_name	    = "testAircall"

asg_desired	    = "1"
asg_max	            = "2"
asg_min	            = "1"
health_check_type   = "ELB"
health_check_grace_period = "300"
backend_name        = "aircalldev"
env                 = "development"
name_ami_filter     = "testAircall-*"
bucket              = "testaircalldev"
db_allocated_storage = "10"
db_storage_type = "gp2"
db_instance_class = "db.t2.micro"
db_username = "aircall"
db_password = "testaircall"
db_engine = "mysql"
